spring.application.name=hospitalManagement

#DB configuration
spring.datasource.url=jdbc:mysql://localhost:3306/hospitalDB
spring.datasource.username=root
spring.datasource.password=root

server.servlet.context-path=/api/v1

spring.jpa.hibernate.ddl-auto=create
spring.jpa.hibernate.driver.class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=false

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql

# security config
#spring.security.user.name=prathmesh
#spring.security.user.password=prath123

jwt.secretKey = mdkjijcejkjnkwqnj32ytu3ygubuubeyubhdbahvhdbvkhavdbyuqwfgb32b723t73gbjbchvcdhvdh


server.address=0.0.0.0
server.port=8080