package com.codingshuttle.youtube.hospitalManagement;

import com.codingshuttle.youtube.hospitalManagement.entity.Insurance;
import com.codingshuttle.youtube.hospitalManagement.entity.Patient;
import com.codingshuttle.youtube.hospitalManagement.entity.type.BloodGroupType;
import com.codingshuttle.youtube.hospitalManagement.repository.PatientRepository;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;

import java.time.LocalDate;

import static org.assertj.core.api.Assertions.assertThat;

@DataJpaTest
public class PatientRepositoryTest {

    @Autowired
    private PatientRepository patientRepository;

    private Patient createPatient(String name, String email) {
        Patient p = new Patient();
        p.setName(name);
        p.setEmail(email);
        p.setGender("Male");
        p.setBirthDate(LocalDate.of(2000, 1, 1));
        p.setBloodGroup(BloodGroupType.A_POSITIVE);

        Insurance insurance = new Insurance();
        insurance.setProvider("LIC");
        insurance.setPolicyNumber("POL123");

        p.setInsurance(insurance);

        return p;
    }

    @Test
    @DisplayName("Find patient by valid name")
    void testFindByName_Valid() {
        Patient patient = createPatient("John", "john@gmail.com");
        patientRepository.save(patient);

        Patient result = patientRepository.findByName("John");

        assertThat(result).isNotNull();
        assertThat(result.getName()).isEqualTo("John");
        assertThat(result.getEmail()).isEqualTo("john@gmail.com");
    }

    @Test
    @DisplayName("Return null when name not found")
    void testFindByName_NotFound() {
        Patient result = patientRepository.findByName("Unknown");

        assertThat(result).isNull();
    }

    @Test
    @DisplayName("Find patient when multiple exist but name is unique")
    void testFindByName_MultiplePatients() {
        patientRepository.save(createPatient("John", "john1@gmail.com"));
        patientRepository.save(createPatient("Mike", "mike@gmail.com"));

        Patient result = patientRepository.findByName("John");

        assertThat(result).isNotNull();
        assertThat(result.getEmail()).isEqualTo("john1@gmail.com");
    }

    @Test
    @DisplayName("Case sensitive name search")
    void testFindByName_CaseSensitive() {
        patientRepository.save(createPatient("Alice", "alice@gmail.com"));

        Patient result = patientRepository.findByName("alice");

        assertThat(result).isNull(); // default behavior
    }

    @Test
    @DisplayName("Patient with insurance should persist and fetch correctly")
    void testFindByName_WithInsurance() {
        Patient patient = createPatient("Ravi", "ravi@gmail.com");
        patientRepository.save(patient);

        Patient result = patientRepository.findByName("Ravi");

        assertThat(result).isNotNull();
        assertThat(result.getInsurance()).isNotNull();
        assertThat(result.getInsurance().getProvider()).isEqualTo("LIC");
    }

    @Test
    @DisplayName("CreatedAt should be auto populated")
    void testCreatedAt_AutoGenerated() {
        Patient patient = createPatient("Sam", "sam@gmail.com");
        patientRepository.save(patient);

        Patient result = patientRepository.findByName("Sam");

        assertThat(result.getCreatedAt()).isNotNull();
    }

    @Test
    @DisplayName("Email must be unique constraint")
    void testUniqueEmailConstraint() {
        Patient p1 = createPatient("A", "same@gmail.com");
        Patient p2 = createPatient("B", "same@gmail.com");

        patientRepository.save(p1);

        try {
            patientRepository.saveAndFlush(p2);
        } catch (Exception e) {
            assertThat(e).isNotNull(); // constraint violation expected
        }
    }
}
